apiVersion: apps/v1
kind: Deployment
metadata:
  name: qr-momo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qr-momo
  template:
    metadata:
      labels:
        app: qr-momo
    spec:
      containers:
      - name: qr-momo
        image: mwene/qrmomojenk:v1
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: qr-momo-service
spec:
  type: NodePort
  selector:
    app: qr-momo
  ports:
  - port: 80
    targetPort: 80
